<head>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-129198675-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-129198675-1');
</script>

<!-- Hotjar Tracking Code for https://naomiclark.github.io/planning-for-calm/ -->
<script>
    (function(h,o,t,j,a,r){
        h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
        h._hjSettings={hjid:1089544,hjsv:6};
        a=o.getElementsByTagName('head')[0];
        r=o.createElement('script');r.async=1;
        r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
        a.appendChild(r);
    })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
</script>
</head>


---
title: "Glossary"
---

<br>

There is a lot of specific mindfulness terms you might encounter so we've put together this handy glossary - we hope it's helpful!

The glossary is continuously growing so keep checking back to find out more.

<br>
<br>


### A

#####Acceptance
<p>
Sometimes people can associate 'acceptance' with passivity or 'giving up', in such that accepting our thoughts means that we are OK with them and don't try to change them. This is a misconception and something that even experienced meditators need to occassionally remind themselves of: acceptance does mean that we approve of the thoughts or that we like them or that we have given up trying to change them. What it means for meditators is the acceptance of their existance. We can accept that a thought exists but we don't have to like it.
To put it another way... we can accept that pineapple pizza toppings exist, but that doesn't mean that we must like them.
<br>

By accepting that the thoughts or distractions exist, we can acknowledge their presence and from there be in a better position to change how we respond to them.
</p>



<br>

### B
#####Bells (Tingsa)
Sometimes meditations can involve bells to help signify certain points in the meditation, typically the beginning and the end. It can be helpful to use bells as a way to initially focus our attention, carefully listening to the sound until it fades.

<br>

#####Body-Scan
A technique in which attention is placed at specific parts of the body and moved to the next following a particular direction as if 'scanning' the body. When focussing attention on a specific location, explore any sensations that arise with a sense of curiosity.

<br>

### D
#####Decentering
The ability to see your thoughts as separate to yourself, as just mental events rather than as absolute truth (Papies et al., 2012).

<br>

### E
#####Eating Meditations / Mindful Eating
A practice in which deliberate attention is placed onto food. In this, you might focus on the taste, texture, smell or anytother characteristic of the food. This practice is typically done using a raisin, but it can be done with any food or even with drinks as long as you are trying to engage your full awareness.

<br>

### H
#####'Happy Place'
No doubt you've often heard of this already! Although it can be viewed as stereotypical, it can actually help people to become mindful and meditate through visualising a calm, relaxing place.

<br>

### J
#####Journey
Mindfulness is sometimes described as a 'journey' in a sense that it helps you get back in touch with yourself and is a personal exploration, often involving various twists and turns.

<br>

### L

#####Loving-Kindness
This is a specific type of meditation which focuses on cultivating feelings of compassion and kindness towards others and yourself.

<br>

### M
#####Meditation
Like mindfulness itself, the definition of 'meditation' is also debated. One view is to understand meditation as being a deliberate practice used to focus your attention, which in turn can increase your ability to be 'mindful'.

<br>

#####Mindfulness
Many different definitions of mindfulness (Black, 2006). One of the more well-known definitions is that proposed by Kabat-Zinn: the ability to deliberately redirect attention to the breath without judgement (Kabat-Zinn, 1993). However, other definitions exist arguing that mindfulness is more to do with being open to and aware of changes and novelty in ones environment (Langer & Moldoveanu, 2000). Typically most studies into mindfulness and its effects understand mindfulness according to the former definition. Although having different definitions can make it difficult to understand what consistitutes mindfulness itself, it does allow for the consideration and exploration of features and functions that some defintions may not.

Mindfulness can be understood as existing as both a 'state' (how mindful you are right now) and as a 'trait' (how mindful you are in general) (Brown & Ryan, 2003). Questionnaires have been designed to measure these two forms, each slightly different in their conceptualisation. A well-known trait mindfulness questionnaire, the Five Facet Mindfulness Questionnaire (Baer et al., 2006), views mindfulness as consisting of five key features or 'facets': non-judgement and non-reaction to thoughts, feelings etc., acting with awareness, observation of feelings and sensations, and the ability to describe those feelings and sensations.

<br>

#####Mindfulness-Based Cognitive Therapy (MCBT)
A cognitive therapy that incorporates elements of mindfulness into its programme.

<br>

#####Mindfulness-Based Stress Reduction (MBSR)
Originally established by Jon Kabat-Zinn in 1982 to help individuals suffering from chronic pain, MBSR has become a standard in mindfulness interventions and aims to help the practitioner cope better with stress.


<br>

### O

#####Open Awareness Meditation
Typically a non-guided meditation that often involves focussing attention externally to your surroundings.



<br>

### T
#####Timed-Meditation
A typically quiet or non-guided meditation track, lasting for a specific amount of time that often uses bells to signal the start and the end.


<br>

### V
#####Visualisation
Some individuals may find that imagining a sunset or placing themselves sitting on a beach or even with a loved one or pet can help them to feel a little calmer and enter into a mindful state more easily. It can help to visualise thoughts as objects that can float away to emphasise the temporary, fleeting nature of thoughts such as letting go of balloons or watching leaves float down a river.

<br>

### Y
#####Yoga
Some people find using gentle movements such as those found in yoga can help them develop and practice mindfulness by paying particular attention to the body. If you are thinking about using exercise, please consult your doctor beforehand to ensure that you can practice it safely.
